version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6378:6378'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "mpscanner.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/mpscanner'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery worker -l info -A mpscanner.blueprints.contact.tasks
    env_file:
      - '.env'
    volumes:
      - '.:/mpscanner'

volumes:
  redis:
